/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import javax.swing.JTextField;
import javax.swing.JLabel;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
/**
 *
 * @author User
 */
public class cekGanjilGenapJFrame extends javax.swing.JFrame {

    /**
     * Creates new form cekGanjilGenapJFrame
     */
    public cekGanjilGenapJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        angkaField = new javax.swing.JTextField();
        btnCek = new javax.swing.JButton();
        genaptField = new javax.swing.JTextField();
        ganjilField = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Cek Angka Ganjil Genap");

        angkaField.setBackground(new java.awt.Color(204, 204, 204));
        angkaField.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        angkaField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                angkaFieldActionPerformed(evt);
            }
        });

        btnCek.setBackground(new java.awt.Color(153, 153, 153));
        btnCek.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCek.setText("Cek");
        btnCek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCekActionPerformed(evt);
            }
        });

        genaptField.setBackground(new java.awt.Color(153, 153, 153));
        genaptField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                genaptFieldFocusGained(evt);
            }
        });
        genaptField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genaptFieldActionPerformed(evt);
            }
        });
        genaptField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                genaptFieldKeyPressed(evt);
            }
        });

        ganjilField.setBackground(new java.awt.Color(153, 153, 153));
        ganjilField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ganjilFieldActionPerformed(evt);
            }
        });

        jTextField1.setBackground(new java.awt.Color(102, 102, 102));
        jTextField1.setForeground(new java.awt.Color(102, 102, 102));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Bilangan Prima");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(289, 289, 289)
                        .addComponent(btnCek))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(227, 227, 227)
                                .addComponent(angkaField, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(68, 68, 68)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(genaptField, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ganjilField, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(jLabel1)))
                .addContainerGap(134, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel1)
                .addGap(49, 49, 49)
                .addComponent(angkaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCek)
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(genaptField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ganjilField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(247, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void angkaFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_angkaFieldActionPerformed
 try {
        // Mendapatkan input dari angkaField dan mengonversinya ke tipe integer
        int angka = Integer.parseInt(angkaField.getText());
        
        // Mengecek apakah angka genap atau ganjil, dan mengubah teks resultLabel sesuai hasil
        if (angka % 2 == 0) {
            jLabel1.setText("Angka " + angka + " adalah Genap.");
        } else {
            jLabel1.setText("Angka " + angka + " adalah Ganjil.");
        }
    } catch (NumberFormatException e) {
        // Menangani kasus input yang bukan angka
            jLabel1.setText("Masukkan angka yang valid.");
    }
    }//GEN-LAST:event_angkaFieldActionPerformed

    private void btnCekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCekActionPerformed
     try {
        // Mendapatkan input dari angkaField dan mengonversinya ke tipe integer
        int angka = Integer.parseInt(angkaField.getText());
        
        // Mengecek apakah angka genap atau ganjil, dan mengubah teks resultLabel sesuai hasil
        if (angka % 2 == 0) {
          genaptField.setText("Angka " + angka + " adalah Genap.");
        } else {
           ganjilField.setText("Angka " + angka + " adalah Ganjil.");
        }
    } catch (NumberFormatException e) {
        // Menangani kasus input yang bukan angka
            jLabel1.setText("Masukkan angka yang valid.");
    }
    }//GEN-LAST:event_btnCekActionPerformed

    private void ganjilFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ganjilFieldActionPerformed
        String input = ganjilField.getText();

        try {
            // Ubah input menjadi angka
            int angka = Integer.parseInt(input);

            // Cek apakah angka ganjil
            if (angka % 2 != 0) {
                // Jika angka ganjil, lakukan sesuatu
                System.out.println(angka + " adalah angka ganjil.");
            } else {
                // Jika angka genap, lakukan sesuatu
                System.out.println(angka + " adalah angka genap.");
            }
        } catch (NumberFormatException e) {
            // Jika input bukan angka, tampilkan pesan error
            System.out.println("Input bukan angka valid.");
        }
    }//GEN-LAST:event_ganjilFieldActionPerformed

    private void genaptFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genaptFieldActionPerformed
        try {
            
            // Mendapatkan input dari genaptField dan mengonversinya ke tipe integer
            int angka = Integer.parseInt(genaptField.getText());

            // Mengecek apakah angka genap
            if (angka % 2 == 0) {
                // Jika angka genap, tampilkan pesan atau lakukan sesuatu
                jLabel1.setText("Angka " + angka + " adalah Genap.");
            } else {
                // Jika angka tidak genap, beri tahu pengguna
                jLabel1.setText("Angka " + angka + " bukan Genap.");
                
            }
            
        } catch (NumberFormatException e) {
            // Menangani kasus input yang bukan angka
            jLabel1.setText("Masukkan angka yang valid.");
            
        }
    }//GEN-LAST:event_genaptFieldActionPerformed

    private void genaptFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_genaptFieldKeyPressed
         genaptField.setText("");
    
    // Cek apakah tombol yang ditekan adalah Enter (kode 10)
    if (evt.getKeyCode() ==  KeyEvent.VK_ENTER) {
        try {
            int angka = Integer.parseInt(genaptField.getText());

            // Mengecek apakah angka genap atau ganjil
            if (angka % 2 == 0) {
                 genaptField.setText(angka + " adalah angka genap.");
            } else {
                 genaptField.setText(angka + " adalah angka ganjil.");
            }
        } catch (NumberFormatException e) {
            // Menangani jika input bukan angka
             genaptField.setText("Masukkan angka yang valid.");
        }
    }
    }//GEN-LAST:event_genaptFieldKeyPressed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void genaptFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_genaptFieldFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_genaptFieldFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cekGanjilGenapJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cekGanjilGenapJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cekGanjilGenapJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cekGanjilGenapJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cekGanjilGenapJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField angkaField;
    private javax.swing.JButton btnCek;
    private javax.swing.JTextField ganjilField;
    private javax.swing.JTextField genaptField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
